### ISSUE TITLE
docker: Invalid ip address: localhost

### ISSUE THREAD

**Issue by JOduMonT** [DFabric/DPlatform-DockerShip#2]
Hi;

Thanks for your awesome works ;)
I look around, it seems more a [docker issue](https://github.com/docker/compose/issues/2493) without solution for now but I don't truly

I found a potential workaround I just wonder where I could change that into your script ;)

> Weve found a bug in the networking proxy that's the likely cause of this. As a very temporary workaround, you can use docker instead of localhost. This will be fixed in the next beta release that's going out this week. The docker hostname will stop working in that release (but localhost will be reliable).

https://forums.docker.com/t/localhost-port-forwarding-causing-invalid-sql-fixed/17719/10

Regards!

Jonathan

PS: I need this kind of config because my firewall is iptables and my lan is the Internet
so using the local network access only == expose the service to the world.

**Comment by j8r** [comment]
Hi @jodumont !
No problem, my script is way to be perfect - I'm glad when people like you enhance it.
 [This line](https://github.com/DFabric/DPlatform-DockerShip/blob/master/dplatform.sh#L150) is very likely what you're looking for.
If changing `localhost` to `docker` doesn't impact others, you're welcome.
